### ISSUE TITLE
Add separate module ID field

### ISSUE THREAD

**Issue by Fripe070** [ThatOtherAndrew/ThatOtherBot#25]
### Checklist

- [x] I am willing to follow this issue and provide additional information and feedback.
- [x] I have searched for a similar feature in this repository and didn't find anything relevant.
- [x] I am willing to provide specific implementation or solution examples to aid design and development.

### Problem
Module names are very limited at the moment, more so acting as IDs rather than human readable names. 

### Solution
Create a distinction between a modules `id` and `name` through adding a new field to the manifest.

### Examples
```toml
name = "A human readable module name!"
id = "programmatically-readable-id"
```

### Attachments

(No attachments)

### Extra information

(No extra information)
